[workspace]
resolver = "2"
members = [
    "bin/mev",
    "bin/utils",
    "mev-boost-rs",
    "mev-relay-rs",
    "mev-build-rs",
    "mev-rs",
]
default-members = ["bin/mev"]

[workspace.package]
version = "0.3.0"

[workspace.dependencies]
ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "6c7305336397b1cfa1c780812a51c97bd025d052" }
beacon-api-client = { git = "https://github.com/ralexstokes/ethereum-consensus", rev = "6c7305336397b1cfa1c780812a51c97bd025d052" }

reth = { git = "https://github.com/paradigmxyz/reth", rev = "71f8e678aa53f75c2c35badaa5848262de594cdc" }
reth-db = { git = "https://github.com/paradigmxyz/reth", rev = "71f8e678aa53f75c2c35badaa5848262de594cdc" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "71f8e678aa53f75c2c35badaa5848262de594cdc" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", rev = "71f8e678aa53f75c2c35badaa5848262de594cdc" }
reth-basic-payload-builder = { git = "https://github.com/paradigmxyz/reth", rev = "71f8e678aa53f75c2c35badaa5848262de594cdc" }

eyre = "0.6.8"
futures-util = "0.3.30"
sha2 = "0.10.8"

[patch.crates-io]
c-kzg = { git = "https://github.com/ethereum/c-kzg-4844", tag = "v1.0.1" }
