network = "sepolia"

[boost]
host = "0.0.0.0"
port = 18550
relays = [
    "https://0x845bd072b7cd566f02faeb0a4033ce9399e42839ced64e8b2adcfc859ed1e8e1a5a293336a49feac6d9a5edb779be53a@boost-relay-sepolia.flashbots.net",
]

[relay]
host = "0.0.0.0"
port = 28545
beacon_node_url = "http://127.0.0.1:5052"
secret_key = "0x24b6e79cbc6267c6e527b4bf7a71747d42a58b10279366cf0c7bb4e2aa455901"
accepted_builders = [
    "0xa4476fe970fdd7bd4050955fa1261f60905ff41165cdbdb77d235589d1a090c3e91ae926eba96db77516d5088734818c",
    "0x97e7aa4df6b120f30c17fcca3771aa9a37d0a873d2fe74b40f30a6b30458785f895fb82e5be304bd5d687ae18d836d73",
    "0x8d48be80acd4aac4123686a01515b36c579e5608ab2114d4d6a7f2af272bb933719cb3b87ac23adb2c3ccec0547557f0",
]

[builder]
# builder BLS secret key
secret_key = "0x14b6e79cbc6267c6e527b4bf7a71747d42a58b10279366cf0c7bb4e2aa455901"
# list of relays to connect to
relays = [
    "https://0x845bd072b7cd566f02faeb0a4033ce9399e42839ced64e8b2adcfc859ed1e8e1a5a293336a49feac6d9a5edb779be53a@boost-relay-sepolia.flashbots.net",
]
# extra data to write into built execution payload
extra_data = "0x68656C6C6F20776F726C640A" # "hello world"
# wallet seed for builder to author payment transactions
execution_mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
# number of milliseconds to submit bids ahead of the target slot
bidding_deadline_ms = 1000
# amount of value to bid as a fraction of the payload's revenue
bid_percent = 0.9
# amount to add to the bid on top of the payload's revenue,
# currently sourced from the builder's wallet authoring the payment transaction
subsidy_gwei = 100000000 # 0.1 eth
